"""Relay checkpoint 06: Azure blob and queue adapters."""

from __future__ import annotations

from .relay_azure import (
    DEFAULT_RETRY_SETTINGS,
    AzureBlobTaskStore,
    AzureQueueTaskDispatcher,
    AzureRetrySettings,
    BlobContainerClientProtocol,
    BlobItemProtocol,
    BlobPagerProtocol,
    BlobServiceClientProtocol,
    BlobServiceFactory,
    QueueClientProtocol,
    QueueServiceClientProtocol,
    QueueServiceFactory,
    RelayAuthenticationError,
    RelayAzureError,
    RelayOperationError,
    RelayPermissionError,
    RelayTaskNotFoundError,
    RelayTaskQueue,
    RelayTaskSnapshot,
    RelayTaskStore,
    TaskState,
    build_blob_task_store,
    build_queue_task_dispatcher,
    default_blob_service_factory,
    default_queue_service_factory,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_RETRY_SETTINGS",
    "AzureBlobTaskStore",
    "AzureQueueTaskDispatcher",
    "AzureRetrySettings",
    "BlobContainerClientProtocol",
    "BlobItemProtocol",
    "BlobPagerProtocol",
    "BlobServiceClientProtocol",
    "BlobServiceFactory",
    "QueueClientProtocol",
    "QueueServiceClientProtocol",
    "QueueServiceFactory",
    "RelayAuthenticationError",
    "RelayAzureError",
    "RelayOperationError",
    "RelayPermissionError",
    "RelayTaskNotFoundError",
    "RelayTaskQueue",
    "RelayTaskSnapshot",
    "RelayTaskStore",
    "TaskState",
    "__version__",
    "build_blob_task_store",
    "build_queue_task_dispatcher",
    "default_blob_service_factory",
    "default_queue_service_factory",
]
