"""Relay worker pool with visibility timeouts and graceful drains."""

from __future__ import annotations

from .accelerators import (
    AcceleratorDevice,
    AcceleratorTopology,
    AcceleratorWorkerPlacement,
    FabricKind,
    PciAddress,
    PciFunction,
    PciTopology,
    RoceCongestionPolicy,
    RoceFabricConfig,
    TransferPlan,
    diagnose_roce_readiness,
    discover_accelerator_topology,
    discover_iommu_group,
    discover_network_topology,
    discover_pci_topology,
    is_accelerator_class,
    is_network_class,
    parse_pci_address,
    peer_to_peer_feasible,
    plan_accelerator_workers,
    plan_transfer,
    requires_ethernet_congestion_policy,
    shared_ancestor_depth,
)
from .models import RelayTask, RelayTaskSnapshot, TaskState
from .multicore import (
    CpuResult,
    CpuWork,
    ProcessRun,
    SharedMemoryRun,
    count_deliveries_with_manager,
    cpu_transform,
    run_process_queue,
    sum_shared_bytes,
)
from .numa import (
    NumaNode,
    NumaTopology,
    NumaWorkerPlacement,
    bind_numa_worker,
    discover_numa_topology,
    numactl_command,
    parse_cpu_list,
    parse_numa_maps,
    pin_current_process,
    plan_numa_workers,
)
from .queue import InMemoryVisibilityQueue, Lease, ManualClock, VisibilityQueue
from .worker_pool import RelayWorkerPool, TaskDisposition, WorkerLostError

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "AcceleratorDevice",
    "AcceleratorTopology",
    "AcceleratorWorkerPlacement",
    "CpuResult",
    "CpuWork",
    "FabricKind",
    "InMemoryVisibilityQueue",
    "Lease",
    "ManualClock",
    "NumaNode",
    "NumaTopology",
    "NumaWorkerPlacement",
    "PciAddress",
    "PciFunction",
    "PciTopology",
    "ProcessRun",
    "RelayTask",
    "RelayTaskSnapshot",
    "RelayWorkerPool",
    "RoceCongestionPolicy",
    "RoceFabricConfig",
    "SharedMemoryRun",
    "TaskDisposition",
    "TaskState",
    "TransferPlan",
    "VisibilityQueue",
    "WorkerLostError",
    "count_deliveries_with_manager",
    "cpu_transform",
    "bind_numa_worker",
    "diagnose_roce_readiness",
    "discover_accelerator_topology",
    "discover_iommu_group",
    "discover_network_topology",
    "discover_numa_topology",
    "discover_pci_topology",
    "is_accelerator_class",
    "is_network_class",
    "numactl_command",
    "parse_cpu_list",
    "parse_numa_maps",
    "parse_pci_address",
    "peer_to_peer_feasible",
    "pin_current_process",
    "plan_accelerator_workers",
    "plan_numa_workers",
    "plan_transfer",
    "requires_ethernet_congestion_policy",
    "run_process_queue",
    "shared_ancestor_depth",
    "sum_shared_bytes",
]
