"""HTTP RPC client and fake service for the relay task service."""

from __future__ import annotations

from lab_19_rpc_service.api import (
    RelayTaskState,
    TaskSubmissionBody,
    app_factory,
    create_app,
)
from lab_19_rpc_service.concurrency import (
    Heartbeat,
    blocking_write,
    offloaded_write,
)
from lab_19_rpc_service.contract import (
    MAX_TARGET_LENGTH,
    MAX_TASK_ID_LENGTH,
    MAX_TIMESTAMP_LENGTH,
    TASKS_COLLECTION_PATH,
    ContractError,
    TaskAction,
    TaskState,
    TaskStatus,
    TaskSubmission,
)
from lab_19_rpc_service.rpc import (
    DeadlineBudget,
    DeadlineExceeded,
    FakeClock,
    FakeTransport,
    HttpRequest,
    HttpResponse,
    IdempotencyConflict,
    RelayHttpService,
    RelayRpcClient,
    RelayRpcError,
    ReplyDroppedError,
    RequestDroppedError,
    RetryDecision,
    RetryOutcome,
    RetryOutcomeKind,
    TaskNotFound,
    TransportFailure,
    TransportFault,
    decide_retry,
)
from lab_19_rpc_service.server import (
    APP_IMPORT_STRING,
    MAX_WORKERS,
    ServerConfig,
    UvloopUnavailableError,
    build_config_from_env,
    resolve_event_loop_name,
    serve,
)

__version__ = "0.1.0"

__all__ = [
    "APP_IMPORT_STRING",
    "MAX_TARGET_LENGTH",
    "MAX_TASK_ID_LENGTH",
    "MAX_TIMESTAMP_LENGTH",
    "MAX_WORKERS",
    "TASKS_COLLECTION_PATH",
    "ContractError",
    "DeadlineBudget",
    "DeadlineExceeded",
    "FakeClock",
    "FakeTransport",
    "Heartbeat",
    "HttpRequest",
    "HttpResponse",
    "IdempotencyConflict",
    "RelayHttpService",
    "RelayRpcClient",
    "RelayRpcError",
    "RelayTaskState",
    "ReplyDroppedError",
    "RequestDroppedError",
    "RetryDecision",
    "RetryOutcome",
    "RetryOutcomeKind",
    "ServerConfig",
    "TaskAction",
    "TaskNotFound",
    "TaskState",
    "TaskStatus",
    "TaskSubmission",
    "TaskSubmissionBody",
    "TransportFailure",
    "TransportFault",
    "UvloopUnavailableError",
    "__version__",
    "app_factory",
    "blocking_write",
    "build_config_from_env",
    "create_app",
    "decide_retry",
    "offloaded_write",
    "resolve_event_loop_name",
    "serve",
]
